### PR TITLE
Add support for ARM and ARM64

### PR DESCRIPTION
**Pull request by ShaharHD**
To build for M1 or arm run the following:

```shell
cmake -G Ninja -DARCH=arm64 ..
cmake -G Ninja -DARCH=arm ..
```

### CODE REVIEW

**Comment by toddwilson** [comment]
@ShaharHD how were you able to build pc-ble-driver-py with this? Thanks for submitting the PR (hope someone at Nordic cares).

**Comment by ShaharHD** [comment]
> @ShaharHD how were you able to build pc-ble-driver-py with this? Thanks for submitting the PR (hope someone at Nordic cares).

@toddwilson Yes.
Even more than that, I got nrf-util working as it should 🥇 

if you're referrning to an M1 specifily here's my whole process:

1. Clone pc-ble-driver and apply the PR:

```shell
git clone https://github.com/NordicSemiconductor/pc-ble-driver.git --branch release/4.1.4
cd pc-ble-driver
git fetch origin pull/271/head:master
git checkout master
```

2. Build pc-ble-driver

```shell
mkdir build
cd build
cmake -G Ninja -DARCH=arm64 -DNRF_BLE_DRIVER_VERSION=4.1.4 -DCONNECTIVITY_VERSION=4.1.4 ..
cmake --build . # you can add -j8 if you want to push it :)
mkdir dist
cmake --install . --prefix dist
```

3.  Go back up
```shell
cd ..
cd ..
```

now inside `pc-ble-driver/build/dist` you have the fully compiled `pc-ble-driver` which you can point to in any other project, like `pc-driver-py`

4. Clone and build pc-ble-driver-py
> I tested only with brew python 3.9 (not with the mac builtin python version)
> make sure you have also have cmake installed
```shell
git clone https://github.com/NordicSemiconductor/pc-ble-driver-py.git --branch release/0.16.2
cd pc-ble-driver-py
python3 -m venv venv
source ./venv/bin/activate
pip3 install --upgrade pip scikit-build
pip3 install -r requirements-dev.txt

export CMAKE_PREFIX_PATH=$(pwd)/../pc-ble-driver/build/dist
export MACOSX_DEPLOYMENT_TARGET=11.0
python3 setup.py bdist_wheel
```

Exit from the venv, simply `exit` fromt the terminal
> we have the venv to keep everything clean in the system

5. And here's the magic
Inside `pc-ble-driver-py/dist` you now have a `whl` file which is all you need to install to any python3 (venv or not venv) and then you can even install `nrfutil` :)

```shell
pip3 install (workdir path from before)\pc-ble-driver-py/dist/pc_ble_driver_py-0.16.2-cp39-cp39-macosx_11_0_arm64.whl
pip3 install nrfutil # if you need this one as well, as pc-ble-driver-py is already satisfied, everything is good
```

**Comment by toddwilson** [comment]
@ShaharHD Thank you!!!

**Review by kenr — APPROVED** [review]
Thanks!

**Comment by ShaharHD** [comment]
> Thanks!

So when do we expect to see v4.1.5?

Please be aware you need to update the build process for the artifacts and the README.md in your CI/CD
Also a much newer vcpkg is required for arm and building for M1 from source requires to specify `-DARCH=arm64`

Once you have this merged and built - you'll also be able to:

1.  Update nrf connect for desktop to be Apple sliicon native
2. pc-ble-driver-py and pc-ble-driver-js can also be arm (not just apple silicon) compatible (for example Raspberry pi)

**Review by kenr — APPROVED** [review]
Thank you for the PR.

**Comment by ShaharHD** [comment]
> > > Thanks!
> > 
> > 
> > So when do we expect to see v4.1.5?
> > Please be aware you need to update the build process for the artifacts and the README.md in your CI/CD Also a much newer vcpkg is required for arm and building for M1 from source requires to specify `-DARCH=arm64`
> > Once you have this merged and built - you'll also be able to:
> > 
> > 1. Update nrf connect for desktop to be Apple sliicon native
> > 2. pc-ble-driver-py and pc-ble-driver-js can also be arm (not just apple silicon) compatible (for example Raspberry pi)
> 
> We are not sure when we are able to release v4.1.5. Most likely we will not precompile and test on M1 because we do not have the capacity in the near feature to look into it.

If you can provide me access to your CI/CD setup - I can assist with it.
You can confirm who I am and my credentials via Nordic's rep in Israel: Boran Technologies.

**Comment by whodeenie** [comment]
It might be worth noting that whilst waiting for native support I'm installed and am running everything through a Rosetta terminal which works well enough. This has saved having to rebuild anything, I'm just running as if I was on an Intel-based Mac.

**Comment by ShaharHD** [comment]
> It might be worth noting that whilst waiting for native support I've installed and am running everything through a Rosetta terminal which works well enough. This has saved having to rebuild anything, I'm just running as if I was on an Intel-based Mac.

Your call on this, but if you are using python or node.js bindings - it then requires you to install also the intel versions of those and intel versions of those tools.

which in my opinion creates even more issues.
my example creates a `pc_ble_driver_py-0.16.2-cp39-cp39-macosx_11_0_arm64.whl` which you can just copy to any machine and you once you install it - it will satisfy and python requirements for pc-ble-driver.

I can do the same for node.js probably.

**Comment by ekrivenja-sequenex** [comment]
We use native libs in internal tooling and Rosetta is not always a solution.
Looking forward for next release, I believe the version might be 4.2 right away :)
@ShaharHD , thank you for this PR!

**Comment by eliaslecomte** [comment]
Hi guys, I'm also trying to compile on my M1 but I have issues when following @ShaharHD's code sample.
When executing `python3 setup.py bdist_wheel` in venv I get:

`CMake Error in CMakeLists.txt:
  Running

   '/Users/eliaslecomte/Sources/madoka/simulator/pc-ble-driver-py/pc_ble_driver_py/venv/bin/ninja' '--version'

  failed with:

   No such file or directory`

Any idea or could you maybe share the .whl driver?

**Comment by ShaharHD** [comment]
> Managed to get everything working. However, on my m1, when using pc-ble-driver-py, when executing `python serial_port_enum.py` it reports 0 devices. (0 serial ports found). 😢

Are you using `pc-ble-driver-py` ?
As this is considered obsolete by Nordic and will not receive any more updates so YMMV with this library moving forward

**Pull request merged**
