### PR TITLE
nRF SDK bootstrap

### PR DESCRIPTION
**Pull request by metc**
Hi Nordic team,

I use a custom home-made board and I had to modify the embedded connectivity application for that board (with a custom UART and board initialization).

I took some time to getting started the first time, so please find in this PR a bash script to download and patch the SDK in order to build the connectivity application with ease. The script is also useful to setup a CI system.

To build the connectivity app, you still need to define `APP_SCHEDULER_WITH_PROFILER` and `HCI_LINK_CONTROL` manually using your preferred IDE/compiler.

Hope this help.

### CODE REVIEW

**Comment by bihanssen** [comment]
Hi, thanks for the PR, this will come in handy.

Question: Are you compiling the connectivity firmware on Linux? Or are you running the script on windows cygwin? I'm asking since the sdk patch is currently only compatible with Keil on Windows.

**Comment by metc** [comment]
Hi,

I tested the script on Linux and on Windows using Git bash (mingw based). The script patches the SDK using the provided `SD20_SDK11.patch`, it does not compile the connectivity application.

I am working making this patch no `__CC_ARM ` specific (see my comment https://github.com/NordicSemiconductor/pc-ble-driver/issues/15#issuecomment-233429311), but my work is not ready to be merged yet. I work on Linux and I use GCC and Eclipse as IDE.

PS: The [ARM Compiler 5](https://developer.arm.com/products/software-development-tools/compilers/arm-compiler-5/downloads) is available on Linux, so technically it's possible to compile the connectivity with the provided patch (need to write a Makefile).

**Comment by metc** [comment]
@bihanssen I changed the permission of the `bootstrap.sh` script. It is now executable.

To apply to patch correctly, we have to deal with Windows and Unix line endings. All the SDK files are CRLF encoded, so applying the patch on Linux or Mac OS could fail...

I saw that a lot of files have a `0755` permission. Is there any reason for this ? If not, I will fix this in another PR next week and I will also fix the line encoding errors we could have between platforms.

**Comment by bihanssen** [comment]
@metc I believe the line endings should be ok on linux/macOS since they are applied with ignore-whitespace (haven't tested though).

Regarding file permissions I see executables and directories having 755 permissions. Did you have any other files in mind?

**Comment by metc** [comment]
I tested the patch on Mac and it doesn't work because of different line ending encoding between the patch and the SDK files. There is maybe a difference on how `patch` and `git apply` work, but it seems that `--ignore-whitespace` has no effect for line endings.

Regarding the files permissions, if you use this command:
```bash
$ cd src/ && git ls-tree HEAD
```
you will see that many source file have a `0755` permission. Is there any reason for that ? If not, I will fix this in a PR next week.

**Comment by bihanssen** [comment]
I see. And no, there should be no reason for the source files to have 755 permissions.

Note: there is work in progress for adapting pc-ble-driver (branch multi-sd) to new versions of SoftDevice API so it might be good to wait with a PR with line ending fixes until that work has settled.

**Comment by metc** [comment]
Yes, I saw this development. I will wait until this work has been merged. Thanks.

**Comment by bihanssen** [comment]
I'm merging this PR now at least, thanks for the contribution.

**Comment by metc** [comment]
Thanks @bihanssen

**Pull request merged**
