### PR TITLE
Experiment/v6 examples update

### PR DESCRIPTION
**Pull request by chunfantasy**
Examples work on nRF52840 Dev Kit.

### CODE REVIEW

**Comment by torfinnberset** [comment]
I'm very eager to try SDv6, but I need a compiled hex file (S132). Can you please add one in `/hex` @chunfantasy? :) Many thanks

**Comment by chunfantasy** [comment]
Hi @torfinnberset,
Thanks for your interest.
Here the compiled hex file is added.
It works with HRC & HRM examples
Since it has not been fully tested yet, it may have bugs.

**Comment by torfinnberset** [comment]
Thanks for he quick update @chunfantasy! 

Unfortunately the 1mbaud serial is not supported on macOS, so I can only use the 115kbaud ones. Also compiling the Connecticity firmware fails on macOS (reported in a separate issue)

**Comment by chunfantasy** [comment]
@torfinnberset Here you are :)

**Comment by torfinnberset** [comment]
Hi again, I tried the hrc_v6 example, but I am getting the following error:

```/Users/torfinn/github/pc-ble-driver/examples/heart_rate_collector/cmake-build-debug/hrc_v6 /dev/tty.usbmodem1411
Serial port used: /dev/tty.usbmodem1411
Baud rate used: 115200
Info: Successfully opened /dev/tty.usbmodem1411. Baud rate: 115200. Flow control: none. Parity: none.

Status: 6, message: Target Reset performed
Failed to open nRF BLE Driver. Error code: 0x0D

Process finished with exit code 13
```

I programmed the `connectivity_2.0.1_115k2_with_s132_6.0.hex` firmware on my nRF52832 Development Kit. If I try the v5 connectivity firmware with hrc_v5, everything works as expected. I also tried programming the `connectivity_2.0.1_1m_with_s132_6.0.hex` firmware just to check, but same error.

**Comment by chunfantasy** [comment]
@torfinnberset Have you programmed softdevice v6 hex file before you program the connectivity v6?

**Comment by torfinnberset** [comment]
@chunfantasy hah indeed, I did not. I thought it was part of the connectivity firmware since I got it working after an erase on SDv5. It works now! Many many many thanks!

**Comment by torfinnberset** [comment]
Hi @chunfantasy, I'm having some issues with the SDv6 branch. When calling `sd_ble_gap_adv_set_configure` with `p_adv_data` argument as NULL, I get a segmentation fault due to it being dereferenced with `app_ble_gap_adv_set_register(*p_adv_handle, p_adv_data->adv_data.p_data, p_adv_data->scan_rsp_data.p_data);`. 

According to the docs, both `p_adv_data` and `p_adv_params` can be `NULL`, but this is not handled correctly in `ble_gap_impl.cpp`:

```
 * @param[in]     p_adv_data                           Advertising data. If set to NULL, no advertising data will be used. See @ref ble_gap_adv_data_t.
 * @param[in]     p_adv_params                         Advertising parameters. When this function is used to update advertising data while advertising,
 *                                                     this parameter must be NULL. See @ref ble_gap_adv_params_t.
```

Furthermore, the branch is missing the SoftDevice headers for S132, but I was able to compile and run it with the S140 headers (I don't know what's the differences between these softdevices)

**Comment by chunfantasy** [comment]
Hi @torfinnberset ,
It has been fixed here https://github.com/NordicSemiconductor/pc-ble-driver/pull/76

**Pull request merged**
